#!/usr/bin/env bash
set -euo pipefail

export TIMEOUT_SEC="${TIMEOUT_SEC:-2400}"
export FLASHINFER_FORCE_JIT_FUSED_MOE_TRTLLM="${FLASHINFER_FORCE_JIT_FUSED_MOE_TRTLLM:-1}"
export FLASHINFER_DEBUG_TRTLLM_BMM_PTRS="${FLASHINFER_DEBUG_TRTLLM_BMM_PTRS:-1}"
export FLASHINFER_DEBUG_TRTLLM_BMM_PTRS_LIMIT="${FLASHINFER_DEBUG_TRTLLM_BMM_PTRS_LIMIT:-4000}"
export RUN_ID="${RUN_ID:-sglang-pure-piecewise-maxbs1024-bmm-ptr-trace-$(date +%Y%m%d-%H%M%S)}"

cd /scratch/repo/sglang

echo "RUN_ID=${RUN_ID}"
echo "TIMEOUT_SEC=${TIMEOUT_SEC}"
echo "FLASHINFER_FORCE_JIT_FUSED_MOE_TRTLLM=${FLASHINFER_FORCE_JIT_FUSED_MOE_TRTLLM}"
echo "FLASHINFER_DEBUG_TRTLLM_BMM_PTRS=${FLASHINFER_DEBUG_TRTLLM_BMM_PTRS}"
echo "FLASHINFER_DEBUG_TRTLLM_BMM_PTRS_LIMIT=${FLASHINFER_DEBUG_TRTLLM_BMM_PTRS_LIMIT}"

bash lab/flashinfer_trtllm_bf16_ima_repro/01.run_default_piecewise_maxbs1024.sh
